language: ruby
rvm:
  - 1.8.7
before_script:
  - 'git clone git://github.com/puppetlabs/puppetlabs-stdlib.git spec/fixtures/modules/stdlib'
script: "rake spec"
branches:
  only:
    - master
    - develop
notifications:
  email:
    - github@razorsedge.org
gemfile: .gemfile
env:
#  - PUPPET_VERSION=2.6.4        # PE 1.1
  - PUPPET_VERSION=2.6.9        # PE 1.2
  - PUPPET_VERSION=2.6.17       # latest 2.6
  - PUPPET_VERSION=2.7.6        # PE 2.0
  - PUPPET_VERSION=2.7.9        # PE 2.0.1+
  - PUPPET_VERSION=2.7.12       # PE 2.5
  - PUPPET_VERSION=2.7.19       # PE 2.6.0
  - PUPPET_VERSION=2.7.20       # latest 2.7
